# Generated by Django 5.1.5 on 2025-08-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victorina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='victorina',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victorina',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
